### ISSUE TITLE
Error when trying to execute the sample code. 

### ISSUE THREAD

**Issue by npampati** [Kopachris/sortxml#1]
Hi @Kopachris,
Getting an error as below, when attempting to execute the code on a sample file.
Could you pls review and confirm if this is a working code or if am missing some setup?
I installed the sortxml module using pip. Error is ofcourse same when attempting to invoke it as a imported module and while independently using the sortxml.py code.
Appreciate your help/review

Stack trace:
C:\>python sortxml.py "sample_graph.xml" "./graph/node/deps" reference -o sorted_sample.xml
Traceback (most recent call last):
  File "C:\sortxml.py", line 252, in <module>
    sorted_xml = sort_xml(xml_doc, sort_path, sort_attr, use_text, as_dt, as_dec, sort_desc)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\sortxml.py", line 199, in sort_xml
    dom = ET.fromstring(xml_str, ET.XMLParser(target=NSTreeBuilder()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python312\Lib\xml\etree\ElementTree.py", line 1323, in XML
    parser.feed(text)
  File "C:\sortxml.py", line 105, in start
    if self._factory is NSElement:
       ^^^^^^^^^^^^^
AttributeError: 'NSTreeBuilder' object has no attribute '_factory'

**Comment by npampati** [comment]
found this article related to the issue.
worked fine after deleting the elementtree.pyd as suggested.
https://www.reddit.com/r/Python/comments/wqay0g/weekend_project_sortxml_a_simple_xml_element/
